name: mohamed_amr_portfolio
description: "Professional Flutter Portfolio - Mohamed Amr"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  url_launcher: ^6.2.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
